/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tw_com_jchang_geniiecgbt_decompNDK */

#ifndef _Included_tw_com_jchang_geniiecgbt_decompNDK
#define _Included_tw_com_jchang_geniiecgbt_decompNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tw_com_jchang_geniiecgbt_decompNDK
 * Method:    decpEcgFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_tw_com_jchang_geniiecgbt_decompNDK_decpEcgFile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
